#!/usr/bin/bash
# Script to setup external display(s). 

# stop if a command is missing
err=0
for cmd in xrandr; do
		command -v $cmd >/dev/null && continue || { echo "$cmd command not found."; err=1; }
done
test $err -eq 1 && exit 1

# create usage from case statement. 
# Strict formatting: space tabbed exactly 2 or 4 depth
# 
#   case "$1" in
#     list)
#     # description line
#     # description line2 
#     # ...
usage_self ()
{
    echo -en "usage: $(basename "$0") ";
    grep  -P '^  {2,4}[^ \(\*]*\)' $0 | sed -e 's/)//g' -e 's/ +/ /g' -e 's/--//g' | xargs | sed 's/ /\|/g' ;
    echo "";
    grep -P '^ {2,4}[^ \(\*]*\)' -A 30 $0 | grep -P -B 1 '^ {2,4}#' | sed -e 's/# //' -e 's/--//g' ;
    echo "";
}

# monitor names with resolution defined=active. no resolution means connected by not active
ACTIVE=$(xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
# laptop always connected, first in name list:
LAPTOP=$(echo "$ACTIVE" | head -1)
# last active. In multimonitor setups will append next monitor to this
ACTIVELAST=$(echo "$ACTIVE" | tail -1)
# all possible monitors detected
CONNECTED=$(xrandr | grep " connected " | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
# all except items already actively connected
OTHER=$(xrandr | grep " connected " | grep -vE " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")

case "$1" in
  list)
  # List available display ports and connection status
		xrandr --query | \
			egrep 'connected|disconnected' | \
			awk '{print $1" "$2}' | \
			sed 's/ connected/ connected <--/' | \
			egrep --color '\S* '
		;;
  connect)
  # Setup external display. 
  # arguments:  [left|right|above|top|below|bottom|mirror] [port] [WxH] [rotate]
  #   default possition assumed left.
  #   default port assumed to be first connected monitor other than laptop lcd
  #   WxH will force scaling onto the --auto default resolution
  #   examples:
  #    $0 left
  #    $0 VGA1 right
  #    $0 mirror VGA1
  #    $0 VGA1 right 1920x1080
  #    $0 VGA1 right rotate
  # in background will remove configuration on disconnect

		#echo -e "ACTIVE:\n$ACTIVE\nCONNECTED:\n$CONNECTED\n"
		#echo -e "LAPTOP:$LAPTOP OTHER:$OTHER\n"

		if [ -z "$OTHER" ]; then
			echo -e "No external connected\nAvailable:"
			$0 list
			exit 1
		fi

		PORT=$(echo "$OTHER" | tail -1)
		POS="--left-of $ACTIVELAST"
		SCALE=""
		ROTATE=""

		for arg in "${@:2}"; do
			case "$arg" in
				right)        POS="--right-of $ACTIVELAST" ;;
				left) 	      POS="--left-of $ACTIVELAST" ;;
				above|top)    POS="--above $ACTIVELAST" ;;
				below|bottom) POS="--below $ACTIVELAST" ;;
				mirror)       POS="" ;;
				rotate)       ROTATE="--rotate right" ;;
				*)
					# XxY resolution argument
					if echo "$arg" | egrep -q '^[0-9]*x[0-9]*$'; then
						echo "scale to $arg"
						SCALE="--scale-from $arg"
					# argument defining port
					elif echo "$CONNECTED" | grep -q "$arg"; then
						PORT="$arg"
					# finally assume argument is port name that isnt connected
					else
						echo "Could not find connected display named \"$arg\""
						$0 list
						exit 1
					fi
			;;
			esac
		done
		echo "Connecting \"$PORT\" at \"$POS\""
		echo xrandr --output $PORT --auto $POS $SCALE $ROTATE
		xrandr --output $PORT --auto $POS $SCALE $ROTATE
		# Once port is disconnected remove the xrandr settings
		(while [ 1 ]; do sleep 1; xrandr | grep -q "$PORT disconnected" && $0 disconnect && break; done) &

		;;
	disconnect)
		# disconnect from first non-laptop
		# assumes monitor is still connected
		PORT=$(echo "$OTHER" | head -1)
		# if disconnect called while monitor connected PORT populated, else not and can just run auto
		test -n "$PORT" && xrandr --output $PORT --off
		# Disconnect display.
		xrandr --auto
	;;

  *)
		usage_self
	;;
esac

exit 0
