#!/usr/bin/env bash
trap 'echo "Error line $LINENO"' ERR # thrown when 'false' called
set -e                               # exit on any error


if [ $# -lt 1 ]; then
    E=$(basename $0)
    echo "ENCRYPT & PUSH:"
    echo "$E ./src.txt   ./file.gpg      # single file"
    echo "$E ./dir       ./dir.gpg       # dir compressed"
    echo "$E ./src.txt   server:file.gpg # to server"
    echo "$E ./src.txt   ./file.gpg -k <email> # encrypt to gpg key"
    echo
    echo "PULL & DECRYPT"
    echo "$E ./dir.gpg       ./"
    echo "$E server:file.gpg ./src.txt"
    echo "$E ./file.gpg      ./file.gpg -b # backup dst"
    echo
    exit 1
fi
SRC=$1
DST=$2
test "$3" == "-b" && BKP=$3
test "$3" == "-k" && KEY=$4
DO="null" # enc&push or pull&dec
echo "$SRC" | grep -E -qi '.gpg$' && DO="pull&dec"
echo "$DST" | grep -E -qi '.gpg$' && DO="enc&push"
[ "$DO" == "null" ] \
  && echo "error: either src or dst must be a .gpg file to indicate push or pull" && exit 1
# set -x
if [ "$DO" == "enc&push" ]; then
    test -e $SRC         || ( echo "$SRC not exist" && false )
    cd $(dirname $SRC)   || ( echo "error" && false )
    SRC=$(basename $SRC)
    if [ -d $SRC ]; then
        tar -czf tmp.tar.gz $SRC || false 
        test "$KEY" = "" \
        && (gpg --symmetric --output $SRC.gpg tmp.tar.gz || false)
        test "$KEY" != "" \
        && (gpg --encrypt --recipient $KEY --output $SRC.gpg tmp.tar.gz || false)
    	rm tmp.tar.gz
    else
        test "$KEY" = "" \
        && (gpg --symmetric --output $SRC.gpg $SRC           || false)
        test "$KEY" != "" \
        && (gpg --encrypt --recipient $KEY --output $SRC.gpg $SRC || false)
    fi
    scp $SRC.gpg $DST                                    || ( echo "err scp $SRC.gpg" && false )
    rm $SRC.gpg
    echo "PULL BACK:"
    echo "$(basename $0) $DST $SRC"
elif [ "$DO" == "pull&dec" ]; then
    # target is dir, else is file
    #if test -d $DST; then
    #    cd $DST
    #    DST="./"
    #fi

    # if src is remote, download
    test ! -e $SRC && (scp $SRC . || false)
    SRCF=$(basename ${SRC#*:})

    file --brief $SRCF | grep -qi 'GPG'         || ( echo "$SRCF not gpg file" && false )

    gpg --output $SRCF.stage --decrypt $SRCF     || ( echo "error gpg -d $SRCF" && exit 1 )
    rm $SRCF

    if file --brief $SRCF.stage | grep -qi 'gzip compressed' ; then
        mv $SRCF.stage $SRCF.gz                  || false
        gzip -d $SRCF.gz --stdout > $SRCF.stage  || false
        rm $SRCF.gz
    fi

    if file --brief $SRCF.stage | grep -qi 'tar archive' ; then
        mv $SRCF.stage $DST/$SRCF.tar           || false
	cd $DST
        tar xvf $SRCF.tar                       || false
        rm $SRCF.tar
        rm $SRCF.stage
    else
        test -n "$BKP" && test -e $DST && cp $DST $DST.$(date +%s)
        mv $SRCF.stage $DST
    fi

    echo "PUSH BACK:"
    echo "$(basename $0) $DST $SRC"
fi
